In [1]:
from mxnet import nd, gluon
from mxnet import autograd as ag
import mxnet as mx
import utils

ctx = utils.try_gpu()

In [2]:
batch_size = 256
epochs = 100
learning_rate =0.5
train_data, test_data = utils.load_data_fashion_mnist(batch_size)
28 * 28

784

In [3]:
num_inputs = 28 * 28
num_hidden_1 = 256 

num_outputs = 10
weight_scale = 0.01

# W1 = nd.random_normal(scale=weight_scale, shape=(num_inputs,num_hidden_1),ctx=ctx)
# b1 = nd.random_normal(scale=weight_scale, shape=num_hidden_1, ctx=ctx)

# W2 = nd.random_normal(scale=weight_scale, shape=(num_hidden_1, num_hidden_1),ctx=ctx)
# b2 = nd.random_normal(scale=weight_scale, shape=num_hidden_1, ctx=ctx)

# W3 = nd.random_normal(scale=weight_scale, shape=(num_hidden_1, num_hidden_1),ctx=ctx)
# b3 = nd.random_normal(scale=weight_scale, shape=num_hidden_1, ctx=ctx)

# W4 = nd.random_normal(scale=weight_scale, shape=(num_hidden_1, num_outputs),ctx=ctx)
# b4 = nd.random_normal(scale=weight_scale, shape=num_outputs, ctx=ctx)

W1 = nd.zeros( shape=(num_inputs,num_hidden_1),ctx=ctx)
b1 = nd.zeros(shape=num_hidden_1, ctx=ctx)

W2 = nd.zeros(shape=(num_hidden_1, num_hidden_1),ctx=ctx)
b2 = nd.zeros( shape=num_hidden_1, ctx=ctx)

W3 = nd.zeros( shape=(num_hidden_1, num_hidden_1),ctx=ctx)
b3 =nd.zeros( shape=num_hidden_1, ctx=ctx)

W4 = nd.zeros( shape=(num_hidden_1, num_outputs),ctx=ctx)
b4 = nd.zeros( shape=num_outputs, ctx=ctx)



params = [W1, b1, W2, b2,W3, b3,W4,b4]
for param in params:
    param.attach_grad()

In [4]:
W1


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 784x256 @cpu(0)>

In [5]:
def relu(yhat):
    return nd.maximum(yhat, 0)

def net(X):
    X = X.reshape((-1, num_inputs))
    h1 = relu(nd.dot(X, W1) + b1)
    h2 = relu(nd.dot(h1, W2) + b2)
    h3 = relu(nd.dot(h2, W3) + b3)
    output = nd.dot(h3, W4) + b4
    return output 

In [6]:
# X, y = next(iter(train_data))
# net(X)


In [7]:
# train_data

In [8]:
loss_SM_CE = gluon.loss.SoftmaxCELoss()


In [ ]:
for e in range(epochs):
    training_loss = 0
    training_acc = 0
    for datas, labels in train_data:
        X = datas.as_in_context(ctx)
        y = labels.as_in_context(ctx)
        with ag.record():
            output = net(X)
            loss = loss_SM_CE(output, y)
        loss.backward()
        utils.SGD(params, learning_rate / batch_size)
        training_loss += nd.mean(loss).asscalar()
        training_acc += utils.accuracy(output, y)
        
#         print(W1)
        
    test_acc = utils.evaluate_accuracy(test_data, net)
    print("Epoch %d. Loss: %f, Train acc %f, Test acc %f" % (
        e, training_loss/len(train_data),
        training_acc/len(train_data), test_acc))
        

Epoch 0. Loss: 2.303096, Train acc 0.100177, Test acc 0.100060
Epoch 1. Loss: 2.303121, Train acc 0.098558, Test acc 0.100160
Epoch 2. Loss: 2.303172, Train acc 0.099025, Test acc 0.100060
Epoch 3. Loss: 2.303118, Train acc 0.097489, Test acc 0.100060
Epoch 4. Loss: 2.303156, Train acc 0.098190, Test acc 0.099960
Epoch 5. Loss: 2.303068, Train acc 0.100010, Test acc 0.099860
Epoch 6. Loss: 2.303116, Train acc 0.100010, Test acc 0.099760
Epoch 7. Loss: 2.303070, Train acc 0.099326, Test acc 0.100060
Epoch 8. Loss: 2.303064, Train acc 0.100210, Test acc 0.099960
Epoch 9. Loss: 2.303097, Train acc 0.100277, Test acc 0.100160
Epoch 10. Loss: 2.303163, Train acc 0.099075, Test acc 0.099860
Epoch 11. Loss: 2.303076, Train acc 0.099192, Test acc 0.099760
Epoch 12. Loss: 2.303133, Train acc 0.099359, Test acc 0.099960
Epoch 13. Loss: 2.303164, Train acc 0.100361, Test acc 0.100060


In [22]:
b4.grad


[  8.56794     -0.26947534  -5.4823885   -3.1695693    7.8765903
   1.8707919  -10.519379    -1.5164168   -2.9589605    5.6008353 ]
<NDArray 10 @cpu(0)>

In [24]:
b4


[-0.01759114  0.00600835  0.00788074  0.01554782 -0.04365265 -0.03215576
  0.05476282 -0.04123136  0.06093884 -0.01051008]
<NDArray 10 @cpu(0)>

In [25]:
W4


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
<NDArray 256x10 @cpu(0)>

In [26]:
b3


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<NDArray 256 @cpu(0)>